accessTokenInterceptor 구현 및 token로컬 저장 로직 구현
DSM-DevLib/DevLib-Android pull request #17
Opened 2024-05-08 08:24 UTC by Leesin0222

## PR 작업 요약
accessTokenInterceptor 구현 및 token로컬 저장 로직을 구현해주었습니다.

## 작업 내용
- ​AccessTokenInterceptor구현
- token 로컬 저장 로직 구현
- 잘못 선언된 api 요청 경로 수정
- AccessTokenInterceptor도입으로 인한 header 어노테이션 제거

## Review 마감 기한
승훈이 하은이 맘대로!

## 추가 사항
![image](https://github.com/DSM-DevLib/DevLib-Android/assets/90879448/67fb2d4c-39bd-45b3-923f-8b802c250b44)
요 함수에 deprecated된 부분 나중에 수정하고, 로컬 로직 자체는 dataStore로 마이그레이션하는 모습 기대하겠습니다~

2024-05-08 14:18 UTC, Tmdhoon2 requested changes

2024-05-08 14:18 UTC, Tmdhoon2 commented on app/src/main/java/team/devlib/android/data/di/NetworkModule.kt
> +            .addInterceptor(httpLoggingInterceptor)
요 부분은 함수가 조금 길다고 생각되서 return 사용해주시면 좋을 것 같습니다!

2024-05-08 14:18 UTC, Tmdhoon2 commented on app/src/main/java/team/devlib/android/data/interceptor/AccessTokenInterceptor.kt
> +        val ignorePath = listOf("/user/auth/")
이 부분은 RequestUrl 클래스에 있는 User.auth로 재사용할 수 있을 것 같아요!

2024-05-08 14:18 UTC, Tmdhoon2 commented on app/src/main/java/team/devlib/android/data/di/StorageModule.kt
> +    ): AuthDataStorage
실제로 해당 요소를 싱글턴으로 주입하려면 @Singleton 어노테이션도 같이 명시를 해야하는것으로 알고 있어요!

2024-05-10 04:01 UTC, Leesin0222 commented
@Tmdhoon2  모두 수정 완

2024-05-10 04:37 UTC, Tmdhoon2 approved these changes

2024-05-10 04:37 UTC, Tmdhoon2 commented
@Leesin0222 고생하셨습니다!

2024-05-11 13:04 UTC, merged